services:
  backend:
    build: ./backend
    expose: 
      - "8000"
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/code/app

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
    depends_on:
      - backend